### PR TITLE
More House, deleted duplicate entry

### PR DESCRIPTION
**Pull request by tim222tim**

### CODE REVIEW

**Comment by jlopp** [comment]
hmmmmmmmm Jefferson Van Drew actually lists "Grayscale Investment Trust" near the top of his disclosure... which I assume is likely their Bitcoin trust...

**Comment by tim222tim** [comment]
Oops. I haven't been scanning for Grayscale. I've been reading through the documents and then doing a few manual text searches to make sure I didn't miss anything. I can make another quick pass and look for that.

**Comment by tim222tim** [comment]
What would you like me to do, Jameson? How about if you merge this one. Then I'll sync and go down the whole list scanning for Grayscale.

**Comment by jlopp** [comment]
No need to re-scan for grayscale; I've been checking for it myself. I think this one is an anomaly because it ought to be listed as "Grayscale Bitcoin Investment Trust"

**Comment by jlopp** [comment]
I've updated Van Drew's entry in a different commit now.

**Comment by tim222tim** [comment]
I get it now. I would have caught it had it been named properly.

**Pull request merged**
