### PR TITLE
Automated updates

### PR DESCRIPTION
**Pull request by chance-on-brink**
# Proposal for Full Automation of Data Updates

The code is currently in a “I just finished a hackathon” state, since I am competing for the bounty, but decided to publish now as I am confident this satisfies the listed requirements, and is ultimately the right approach. I will continue to clean up the code, make dependencies easy to install, easy to run, etc.

## Approach Overview

The approach relies on feeding images and prompts into the GPT-4o-mini API for automated parsing. This end-to-end approach by-far outperforms OCR libraries and other fragmented LLM-based workflows. It is also orders of magnitude easier to implement and continue to develop.

### Steps:
1. **Dynamic Retrieval of Current Congress Members**
2. **Direct Data Extraction**
    * For digital, easy-to-read files, asset names are pulled directly and saved to a CSV in the `./all_processed_data` folder.
3. **PDF and GIF Processing**
    * Converts PDF and GIF files into multiple JPEGs. These images are then processed via the OpenAI chat/completions multimodal endpoint, which extracts asset names and saves them to `./all_processed_data`.
4. **Identify Bitcoin/Crypto Assets**
    * uses a set list of terms to identify members with bitcoin/crypto assets

#### More Specifically
1. **gather_source_data.py**
    * Retrieves congress member data from Congress API: https://api.congress.gov/v3/member/congress
    * Scrapes data from the House and Senate financial disclosure sites:
        * House Financial Disclosures: https://disclosures-clerk.house.gov/
        * Senate Financial Disclosures: https://efdsearch.senate.gov/
    * Organizes data for processing and converts PDF/GIF files to JPEGs.
2. **run_parse_asset_names_llm.py**
    * Sends images to OpenAI's API with specific prompts, extracting asset names and saving them to `./all_processed_data`.
3. **final_data_processing.py**
    * Combines files in `./all_processed_data` into `final_asset_data.csv` and `final_summary_data.csv`.
    * Implements bitcoin/crypto term classification based on a predefined list.

It works sufficiently well as-is to detect the bitcoin/crypto terms. The following ideas could improve the asset list for all assets, beyond just bitcoin/crypto related assets.

### Areas for Improvement:
* Better method for image rotation. Assumptions can be made for most files, but sometimes an image will be rotated incorrectly, which hurts the LLM performance.
* Use gpt-4o instead of gpt-4o-mini (current choice to save $).
    * I have experimented with this on select files and it does seem to be markedly better.
* Refine prompts.
* Crop images intelligently to focus on relevant sections.
* Currently asking the LLM when to skip a file. This may be counter-productive. Consider just one-shot prompt each image.
* Directly ask the LLM, does this image mention bitcoin or cryptocurrency? not sure if this will work, might encourage hallucination. worth testing.
* links to all sources are available in the data scraping process, need to write them to file for easy inclusion in the main readMe

### Additional Considerations
The code takes several hours to run (lots of room to make it faster), and costs ~$20 for the OpenAI API with gpt-4o-mini. However, the `all_source_data` and `final_data` folders are small enough to commit to GitHub, so ideally 1 person can run this code periodically, and everyone else can just easily access these artifacts for their own use (unless you are contributing to development of the automation)

Anyone that can find missed bitcoin/crypto investments in the source documents please do point them out. It will help make the process more robust. I have not found any at the time of writing, but I’m sure they exist.

The goal so far was just to identify bitcoin/crypto holdings, but I can think of tons of cool analyses to be done with the final asset names dataset. Hopefully, it will be put to good use.

### CODE REVIEW

**Comment by chance-on-brink** [comment]
here are the differences I have found from the current status of the readMe:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/lee/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/lee/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">



</head>

<body link="#467886" vlink="#96607D">


name | previous holder | current holder | asset_names | note
-- | -- | -- | -- | --
Daniel Goldman | No | Yes | Coinbase Global, Inc. - Class A (COIN) [ST] |  
Garret Graves | No | Yes | Coinbase Global, Inc. - Class A Common Stock (COIN) [ST] |  
Ashley Hinson Areholz | No | Yes | Grayscale Bitcoin Trust - GBTC [MF] |  
Shri Thanedar | No | Yes | Bitcoin, Ethereum |  
Barry Moore | Yes | No |   | previously 'brokerage cryptocurrency', no longer present in 2023   disclosures
Cynthia Lummis | Yes | No |   | bitcoin with unchained ($100,001 - $250,000) disclosed in 2020, no longer   disclosed in latest 2023 disclosures
Michael McCaul | Yes | No |   | <$15k Grayscale in childrens trust in 2021 disclosure, no longer   present in 2023 disclosure
JD Vance | Yes | Yes | BTCExchange/Platform: Coinbase |  
Jefferson Van Drew | Yes | Yes | Greyscale Investment Trust |  
Michael Waltz | Yes | Yes | Bitcoin [OT] |  
Mike Collins | Yes | Yes |   | disclosed ETH purchase transactions (not present in assets section)
Ted Cruz | Yes | Yes | Bitcoin Exchange/Platform: River Financial Inc |  



</body>

</html>

**Comment by jlopp** [comment]
Great, thanks!

I did note the Lummis change recently and it's an awkward situation because it seems the bitcoin was moved into a blind trust. https://x.com/lopp/status/1824414232160428148

I'll check out the code and give it a test run as soon as I can.

**Comment by chance-on-brink** [comment]
found one more with the term 'crypto'
Lauren Boebert: "Robinhood Account Crypto Money Movement COIN"

not sure what this means, maybe coinbase stock?

**Comment by jlopp** [comment]
Weird; sounds like coinbase stock to me. Can't find any crypto tokens with a name like that.

**Comment by chance-on-brink** [comment]
Re-pulled source data on 11/24. Found 0 new disclosures.

**Comment by jlopp** [comment]
Alright I got everything set up and am working on doing a full run.

Executed gather_source_data.py and it pulled 15 PDfs before getting into a failure loop with:

```
16 / 539
Tammy, Baldwin D WI Senate
Attempt 1 failed with error: Message: session not created
from unknown error: cannot find Chrome binary
Stacktrace:
#0 0x60ab7addc31a <unknown>
#1 0x60ab7a8f26e0 <unknown>
#2 0x60ab7a927775 <unknown>
#3 0x60ab7a925926 <unknown>
#4 0x60ab7a9716f6 <unknown>
#5 0x60ab7a970d46 <unknown>
#6 0x60ab7a965203 <unknown>
#7 0x60ab7a933cc0 <unknown>
#8 0x60ab7a934c9e <unknown>
#9 0x60ab7ada9d0b <unknown>
#10 0x60ab7adadc92 <unknown>
#11 0x60ab7ad96b3c <unknown>
#12 0x60ab7adae807 <unknown>
#13 0x60ab7ad7c0df <unknown>
#14 0x60ab7adcb578 <unknown>
#15 0x60ab7adcb740 <unknown>
#16 0x60ab7addb196 <unknown>
#17 0x78278ec94ac3 <unknown>
. Retrying in 60 seconds...
```

**Comment by jlopp** [comment]
Doing a test run on my linux machine; going to make a few improvements to the documentation to account for configuration issues I'm hitting but fingers crossed. Will post any blockers as I come across them. Had a few issues with Chrome but figured out how to resolve them.

**Comment by chance-on-brink** [comment]
great. let me know ifI can help.

**Comment by yes2crypto1** [comment]
Hey @chance-on-brink I added $500 to the $4000 bounty that @jlopp did .  I'm not sure how bountycaster interacts with X since I've only used it in frames on Farcaster, but if we can determine how jlopp paid, I can process my bounty as well.

Congrats!

**Pull request merged**
