### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by CoderBoogs**
Updated Andy Biggs (REP) AZ

### CODE REVIEW

**Comment by jlopp** [comment]
Looks like this is his 2017 annual report; the most recent (2020 annual report) is https://disclosures-clerk.house.gov/public_disc/financial-pdfs/2020/10041364.pdf

**Comment by CoderBoogs** [comment]
My apologies still learning how to use Github correctly.

**Review by CoderBoogs — COMMENTED** [review]
Updated link and report source to the correct year

**Comment by jlopp** [comment]
👍🏼 thanks

**Pull request merged**
